spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tutoring
    username: root
    password: 1558

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml